local opt = vim.opt

opt.scrolloff = 10
opt.number = true
opt.relativenumber = true
opt.showmode = false
opt.showcmd = true
opt.ruler = true
opt.clipboard = "unnamedplus"
opt.ignorecase = true
opt.smartcase = true
opt.incsearch = true
opt.hlsearch = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.updatetime = 250
opt.splitright = true
opt.splitbelow = true
opt.wrap = false
opt.cursorline = true
